// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9KVrCdJ3P3u5IIhMWjipKUgl_f45eXtw',
    appId: '1:973504906260:web:89cbae2063105a3caad301',
    messagingSenderId: '973504906260',
    projectId: 'flutter-firestore-exampl-aefd6',
    authDomain: 'flutter-firestore-exampl-aefd6.firebaseapp.com',
    storageBucket: 'flutter-firestore-exampl-aefd6.firebasestorage.app',
    measurementId: 'G-H5XEBHQMJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-ID8bmRbedoVh-EvSKsG130LMgC9wYrw',
    appId: '1:973504906260:android:05c3103e3fd8097eaad301',
    messagingSenderId: '973504906260',
    projectId: 'flutter-firestore-exampl-aefd6',
    storageBucket: 'flutter-firestore-exampl-aefd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEeD-BkAcrdrT_UJrrzTxI5lIHRsIdy1I',
    appId: '1:973504906260:ios:adaf35c667221ff7aad301',
    messagingSenderId: '973504906260',
    projectId: 'flutter-firestore-exampl-aefd6',
    storageBucket: 'flutter-firestore-exampl-aefd6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirestoreExample',
  );
}
